name: Build TDM Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      working-directory: ${{ github.workspace }}
      run: docker build ${GITHUB_WORKSPACE} --file docker/Dockerfile --tag tdm-novnc:$(date +%s)
