name: Build TDM Docker Image

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive 

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('docker/**') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Show Docker Buildx Info
      run: docker buildx inspect --bootstrap

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with: 
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}

    - name: Build and Push Multi Arch Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: docker/Dockerfile
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.sha }}
        push: true
