name: Build TDM Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      working-directory: ${{ github.workspace }}
      run: docker build . --file docker/Dockerfile --tag tdm-novnc:${{ github.sha }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with: 
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag Docker image
      run: docker tag tdm-novnc:${{ github.sha }} ghcr.io/${{ github.repository }}/tdm-novnc:latest

    - name: Push to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}/tdm-novnc:latest