name: Build TDM Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "docker/**"
      - "tdm/**"
      - ".github/**"
      - "!.github/ISSUE_TEMPLATE/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "docker/**"
      - "tdm/**"
      - ".github/**"
      - "!.github/ISSUE_TEMPLATE/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with: 
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Multi Arch Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.sha }}
        push: true
