name: Publish Image

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/reusable-docker-build.yaml
    with:
      push: true
      platforms: "linux/amd64,linux/arm64"
    secrets: inherit
