name: PR Build

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/reusable-docker-build.yaml
    with:
      push: false
      platforms: "linux/amd64,linux/arm64"
